#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 03 13:20:14 IST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=
